# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Dropbox\Projects\Spectacle\Spectacle_Button_Input_Board\Firmware\Spectacle_Button_Input_Board\Spectacle_Button_Input_Board.cydsn\Spectacle_Button_Input_Board.cyprj
# Date: Wed, 05 Apr 2017 15:15:58 GMT
#set_units -time ns
create_clock -name {EZI2C_SCBCLK(FFB)} -period 125 -waveform {0 62.5} [list [get_pins {ClockBlock/ff_div_0}]]
create_clock -name {UART_SCBCLK(FFB)} -period 8687.5 -waveform {0 4343.75} [list [get_pins {ClockBlock/ff_div_1}]]
create_clock -name {CyILO} -period 25000 -waveform {0 12500} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFCLK} -period 25000 -waveform {0 12500} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyIMO} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFCLK} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySYSCLK} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/sysclk}]]
create_generated_clock -name {EZI2C_SCBCLK} -source [get_pins {ClockBlock/hfclk}] -edges {1 7 13} [list]
create_generated_clock -name {UART_SCBCLK} -source [get_pins {ClockBlock/hfclk}] -edges {1 417 835} [list]


# Component constraints for C:\Dropbox\Projects\Spectacle\Spectacle_Button_Input_Board\Firmware\Spectacle_Button_Input_Board\Spectacle_Button_Input_Board.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Dropbox\Projects\Spectacle\Spectacle_Button_Input_Board\Firmware\Spectacle_Button_Input_Board\Spectacle_Button_Input_Board.cydsn\Spectacle_Button_Input_Board.cyprj
# Date: Wed, 05 Apr 2017 15:15:57 GMT
